export const categories = [
  {
    id: "phrases",
    label: "Necessidades",
    image: "images/frases/estou_com.png",
    children: [
      {
        id: "eu_quero",
        label: "Eu quero",
        image: "images/frases/quero.png",
      },
      {
        id: "estou_com",
        label: "Estou com",
        image: "images/frases/estou_com.png",
      },
      {
        id: "preciso_de",
        label: "Preciso de",
        image: "images/frases/preciso_de.png",
      },
      {
        id: "estou_sentindo",
        label: "Estou sentindo",
        image: "images/frases/estou_sentindo.png",
      },
      { id: "me_ajuda", label: "Me ajuda" },
      { id: "nao_consigo", label: "Não consigo" },
      { id: "quero_ir", label: "Quero ir" },
      { id: "quero_ficar", label: "Quero ficar" },
      { id: "preciso_ir", label: "Preciso ir" },
    ],
  },
  {
    id: "communication",
    label: "Comunicação",
    image: "images/frases/estou_com.png",
    children: [
      { id: "sim", label: "Sim" },
      { id: "nao", label: "Não" },
      { id: "por_favor", label: "Por favor" },
      { id: "obrigada", label: "Obrigada" },
      { id: "desculpa", label: "Desculpa" },
      { id: "ajuda", label: "Ajuda" },
      { id: "nao_entendi", label: "Não entendi" },
      { id: "repete", label: "Repete, por favor" },
      { id: "espera", label: "Espera" },
    ],
  },
  {
    id: "feelings",
    label: "Sentimentos",
    image: "images/sentimentos/sentimentos.png",
    children: [
      {
        id: "dor",
        label: "Dor",
        image: "images/sentimentos/dor.png",
      },
      {
        id: "fome",
        label: "Fome",
        image: "images/sentimentos/dor.png",
      },
      {
        id: "sede",
        label: "Sede",
        image: "images/sentimentos/dor.png",
      },
      {
        id: "triste",
        label: "Triste",
        image: "images/sentimentos/triste.png",
      },
      {
        id: "feliz",
        label: "Feliz",
        image: "images/sentimentos/feliz.png",
      },
      {
        id: "cansada",
        label: "Cansada",
        image: "images/sentimentos/cansada.png",
      },
      {
        id: "frio",
        label: "Frio",
        image: "images/sentimentos/frio.png",
      },
      {
        id: "calor",
        label: "Calor",
        image: "images/sentimentos/feliz.png",
      },
      {
        id: "medo",
        label: "Medo",
        image: "images/sentimentos/medo.png",
      },
      { id: "bem", label: "Bem" },
      { id: "mal", label: "Mal" },
      { id: "cansada", label: "Cansada" },
      { id: "fraca", label: "Fraca" },
      { id: "ansiosa", label: "Ansiosa" },
      { id: "nervosa", label: "Nervosa" },
      { id: "calma", label: "Calma" },
      { id: "confusa", label: "Confusa" },
      { id: "sozinha", label: "Sozinha" },
      { id: "entediada", label: "Entediada" },
    ],
  },
  {
    id: "actions",
    label: "Ações",
    image: "images/acoes/acoes.png",
    children: [
      { id: "comer", label: "Comer" },
      { id: "beber", label: "Beber" },
      { id: "dormir", label: "Dormir" },
      { id: "descansar", label: "Descansar" },
      { id: "sentar", label: "Sentar" },
      { id: "levantar", label: "Levantar" },
      { id: "ir_banheiro", label: "Ir ao banheiro" },
      { id: "tomar_banho", label: "Tomar banho" },
    ],
  },
  {
    id: "people",
    label: "Pessoas",
    image: "images/pessoas/pessoas.png",
    children: [
      { id: "cuidadora", label: "Cuidadora" },
      { id: "filha", label: "Filha" },
      { id: "filho", label: "Filho" },
      { id: "familia", label: "Família" },
      { id: "medica", label: "Médica" },
      { id: "enfermeira", label: "Enfermeira" },
    ],
  },
  {
    id: "time",
    label: "Tempo",
    image: "images/tempo/tempo.png",
    children: [
      { id: "agora", label: "Agora" },
      { id: "depois", label: "Depois" },
      { id: "hoje", label: "Hoje" },
      { id: "amanha", label: "Amanhã" },
      { id: "muito", label: "Muito" },
      { id: "pouco", label: "Pouco" },
    ],
  },
  {
    id: "food",
    label: "Comida",
    image: "images/comida/comida.png",
    children: [
      {
        id: "agua",
        label: "Água",
        image: "images/comida/agua.png",
      },
      {
        id: "arroz",
        label: "Arroz",
        image: "images/comida/arroz.png",
      },
      {
        id: "feijao",
        label: "Feijão",
        image: "images/comida/feijao.png",
      },
      {
        id: "carne",
        label: "Carne",
        image: "images/comida/carne.png",
      },
      {
        id: "pao",
        label: "Pão",
        image: "images/comida/pao.png",
      },
      {
        id: "leite",
        label: "Leite",
        image: "images/comida/leite.png",
      },
      {
        id: "fruta",
        label: "Fruta",
        image: "images/comida/fruta.png",
      },
      {
        id: "doce",
        label: "Doce",
        image: "images/comida/doce.png",
      },
    ],
  },

  {
    id: "bodyparts",
    label: "Corpo",
    image: "images/corpo/cabeca.png",
    children: [
      {
        id: "cabeca",
        label: "Cabeça",
        image: "images/corpo/cabeca.png",
      },
      {
        id: "olho",
        label: "Olho",
        image: "images/corpo/olho.png",
      },
      {
        id: "ouvido",
        label: "Ouvido",
        image: "images/corpo/ouvido.png",
      },
      {
        id: "boca",
        label: "Boca",
        image: "images/corpo/boca.png",
      },
      {
        id: "garganta",
        label: "Garganta",
        image: "images/corpo/garganta.png",
      },
      {
        id: "peito",
        label: "Peito",
        image: "images/corpo/peito.png",
      },
      {
        id: "barriga",
        label: "Barriga",
        image: "images/corpo/barriga.png",
      },
      {
        id: "braco",
        label: "Braço",
        image: "images/corpo/braco.png",
      },
      {
        id: "perna",
        label: "Perna",
        image: "images/corpo/pernas.png",
      },
      {
        id: "pes",
        label: "Pés",
        image: "images/corpo/pes.png",
      },
    ],
  },
];
