export const categories = [
  {
    id: "phrases",
    label: "Necessidades",
    image: "/images/frases/necessidades.png",
    children: [
      {
        id: "estou_com",
        label: "Estou com",
        image: "/images/frases/estou_com.png",
      },
      { id: "eu_quero", label: "Eu quero", image: "/images/frases/quero.png" },
      {
        id: "me_ajuda",
        label: "Me ajuda",
        image: "/images/frases/me_ajuda.png",
      },
      {
        id: "nao_consigo",
        label: "Não consigo",
        image: "/images/frases/nao_consigo.png",
      },
      {
        id: "preciso_de",
        label: "Preciso de",
        image: "/images/frases/preciso_de.png",
      },
      {
        id: "preciso_ir",
        label: "Preciso ir",
        image: "/images/frases/preciso_ir.png",
      },
      {
        id: "quero_ficar",
        label: "Quero ficar",
        image: "/images/frases/quero_ficar.png",
      },
      {
        id: "quero_ir",
        label: "Quero ir",
        image: "/images/frases/quero_ir.png",
      },
      { id: "nao_quero", label: "Não quero" },
      { id: "quero_parar", label: "Quero parar" },
      { id: "quero_continuar", label: "Quero continuar" },
      { id: "preciso_descansar", label: "Preciso descansar" },
      { id: "preciso_ajuda", label: "Preciso de ajuda" },
      { id: "quero_mudar", label: "Quero mudar" },
      { id: "quero_silencio", label: "Quero silêncio" },
      { id: "chega", label: "Chega" },
    ],
  },
  {
    id: "communication",
    label: "Comunicação",
    image: "/images/comunicacao/comunicacao.png",
    children: [
      { id: "sim", label: "Sim", image: "/images/comunicacao/sim.png" },
      { id: "nao", label: "Não", image: "/images/comunicacao/nao.png" },
      {
        id: "desculpa",
        label: "Desculpa",
        image: "/images/comunicacao/desculpa.png",
      },
      {
        id: "espera",
        label: "Espera",
        image: "/images/comunicacao/espera.png",
      },
      { id: "muito", label: "Muito", image: "/images/comunicacao/muito.png" },
      { id: "pouco", label: "Pouco", image: "/images/comunicacao/pouco.png" },
      {
        id: "nao_entendi",
        label: "Não entendi",
        image: "/images/comunicacao/nao_entendi.png",
      },
      {
        id: "obrigada",
        label: "Obrigada",
        image: "/images/comunicacao/obrigada.png",
      },
      {
        id: "por_favor",
        label: "Por favor",
        image: "/images/comunicacao/por_favor.png",
      },
      {
        id: "repete",
        label: "Repete, por favor",
        image: "/images/comunicacao/repete.png",
      },
      { id: "tudo_bem", label: "Tudo bem" },
      { id: "nao_gosto", label: "Não gosto" },
      { id: "gosto", label: "Gosto" },
      { id: "ok", label: "Ok" },
      { id: "agora_nao", label: "Agora não" },
      { id: "mais", label: "Mais" },
      { id: "menos", label: "Menos" },
      { id: "devagar", label: "Devagar" },
      { id: "rapido", label: "Rápido" },
      { id: "assim_esta_bom", label: "Assim está bom" },
      { id: "nao_assim", label: "Não assim" },
      { id: "de_novo", label: "De novo" },
    ],
  },
  {
    id: "feelings",
    label: "Sentimentos",
    image: "/images/sentimentos/sentimentos.png",
    children: [
      {
        id: "estou_sentindo",
        label: "Estou sentindo",
        image: "/images/frases/estou_sentindo.png",
      },
      {
        id: "ansiosa",
        label: "Ansiosa",
        image: "/images/sentimentos/ansiosa.png",
      },
      { id: "bem", label: "Bem", image: "/images/sentimentos/bem.png" },
      { id: "calma", label: "Calma", image: "/images/sentimentos/calma.png" },
      { id: "calor", label: "Calor", image: "/images/sentimentos/feliz.png" },
      {
        id: "cansada",
        label: "Cansada",
        image: "/images/sentimentos/cansada.png",
      },
      {
        id: "confusa",
        label: "Confusa",
        image: "/images/sentimentos/confusa.png",
      },
      { id: "dor", label: "Dor", image: "/images/sentimentos/dor.png" },
      {
        id: "entediada",
        label: "Entediada",
        image: "/images/sentimentos/entediada.png",
      },
      { id: "feliz", label: "Feliz", image: "/images/sentimentos/feliz.png" },
      { id: "fome", label: "Fome", image: "/images/sentimentos/fome.png" },
      { id: "fraca", label: "Fraca", image: "/images/sentimentos/fraca.png" },
      { id: "frio", label: "Frio", image: "/images/sentimentos/frio.png" },
      { id: "mal", label: "Mal", image: "/images/sentimentos/mal.png" },
      { id: "medo", label: "Medo", image: "/images/sentimentos/medo.png" },
      {
        id: "nervosa",
        label: "Nervosa",
        image: "/images/sentimentos/nervosa.png",
      },
      { id: "sede", label: "Sede", image: "/images/sentimentos/sede.png" },
      {
        id: "sozinha",
        label: "Sozinha",
        image: "/images/sentimentos/sozinha.png",
      },
      {
        id: "triste",
        label: "Triste",
        image: "/images/sentimentos/triste.png",
      },
      { id: "desconfortavel", label: "Desconfortável" },
      { id: "irritada", label: "Irritada" },
      { id: "preocupada", label: "Preocupada" },
      { id: "aliviada", label: "Aliviada" },
      { id: "assustada", label: "Assustada" },
      { id: "desconfortavel", label: "Desconfortável" },
      { id: "enjoada", label: "Enjoada" },
      { id: "sonolenta", label: "Sonolenta" },
      { id: "entusiasmada", label: "Entusiasmada" },
    ],
  },
  {
    id: "actions",
    label: "Ações",
    image: "/images/acoes/acoes.png",
    children: [
      { id: "beber", label: "Beber", image: "/images/acoes/beber.png" },
      { id: "comer", label: "Comer", image: "/images/acoes/comer.png" },
      {
        id: "descansar",
        label: "Descansar",
        image: "/images/acoes/descansar.png",
      },
      { id: "dormir", label: "Dormir", image: "/images/acoes/dormir.png" },
      {
        id: "ir_banheiro",
        label: "Ir ao banheiro",
        image: "/images/acoes/ir_ao_banheiro.png",
      },
      {
        id: "levantar",
        label: "Levantar",
        image: "/images/acoes/levantar.png",
      },
      { id: "sentar", label: "Sentar", image: "/images/acoes/sentar.png" },
      {
        id: "tomar_banho",
        label: "Tomar banho",
        image: "/images/acoes/tomar_banho.png",
      },
      {
        id: "trocar_fralda",
        label: "Trocar Fralda",
        image: "/images/acoes/trocar_fralda.png",
      },
      { id: "andar", label: "Andar" },
      { id: "deitar", label: "Deitar" },
      { id: "virar", label: "Virar" },
      { id: "alongar", label: "Alongar" },
      { id: "ligar", label: "Ligar" },
      { id: "desligar", label: "Desligar" },
      { id: "trocar_roupa", label: "Trocar roupa" },
    ],
  },
  {
    id: "people",
    label: "Pessoas",
    image: "/images/pessoas/pessoas.png",
    children: [
      {
        id: "cuidadora",
        label: "Cuidadora",
        image: "/images/pessoas/cuidadora.png",
      },
      {
        id: "enfermeira",
        label: "Enfermeira",
        image: "/images/pessoas/enfermeira.png",
      },
      { id: "familia", label: "Família", image: "/images/pessoas/familia.png" },
      { id: "filha", label: "Filha", image: "/images/pessoas/filha.png" },
      { id: "filho", label: "Filho", image: "/images/pessoas/filho.png" },
      { id: "medica", label: "Médica", image: "/images/pessoas/medica.png" },
      { id: "mae", label: "Mãe" },
      { id: "pai", label: "Pai" },
      { id: "irma", label: "Irmã" },
      { id: "irmao", label: "Irmão" },
      { id: "amiga", label: "Amiga" },
      { id: "amigo", label: "Amigo" },
    ],
  },
  {
    id: "time",
    label: "Tempo",
    image: "/images/tempo/tempo.png",
    children: [
      { id: "agora", label: "Agora", image: "/images/tempo/agora.png" },
      { id: "depois", label: "Depois", image: "/images/tempo/depois.png" },
      { id: "hoje", label: "Hoje", image: "/images/tempo/hoje.png" },
      { id: "amanha", label: "Amanhã", image: "/images/tempo/amanha.png" },
      { id: "cedo", label: "Cedo" },
      { id: "tarde", label: "Tarde" },
      { id: "noite", label: "Noite" },
      { id: "sempre", label: "Sempre" },
      { id: "nunca", label: "Nunca" },
      { id: "as_vezes", label: "Às vezes" },
    ],
  },
  {
    id: "food",
    label: "Comida",
    image: "/images/comida/comida.png",
    children: [
      { id: "agua", label: "Água", image: "/images/comida/agua.png" },
      { id: "arroz", label: "Arroz", image: "/images/comida/arroz.png" },
      { id: "carne", label: "Carne", image: "/images/comida/carne.png" },
      { id: "doce", label: "Doce", image: "/images/comida/doce.png" },
      { id: "feijao", label: "Feijão", image: "/images/comida/feijao.png" },
      { id: "fruta", label: "Fruta", image: "/images/comida/fruta.png" },
      { id: "leite", label: "Leite", image: "/images/comida/leite.png" },
      { id: "pao", label: "Pão", image: "/images/comida/pao.png" },
      { id: "cafe", label: "Café" },
      { id: "cha", label: "Chá" },
      { id: "suco", label: "Suco" },
      { id: "biscoito", label: "Biscoito" },
      { id: "sopa", label: "Sopa" },
      { id: "ovo", label: "Ovo" },
      { id: "macarrao", label: "Macarrão" },
    ],
  },

  {
    id: "bodyparts",
    label: "Corpo",
    image: "/images/corpo/corpo.png",
    children: [
      {
        id: "cabeca",
        label: "Cabeça",
        image: "/images/corpo/cabeca.png",
      },
      {
        id: "olho",
        label: "Olho",
        image: "/images/corpo/olho.png",
      },
      {
        id: "ouvido",
        label: "Ouvido",
        image: "/images/corpo/ouvido.png",
      },
      {
        id: "boca",
        label: "Boca",
        image: "/images/corpo/boca.png",
      },
      {
        id: "garganta",
        label: "Garganta",
        image: "/images/corpo/garganta.png",
      },
      { id: "ombro", label: "Ombro" },
      {
        id: "peito",
        label: "Peito",
        image: "/images/corpo/peito.png",
      },
      { id: "costas", label: "Costas" },
      {
        id: "barriga",
        label: "Barriga",
        image: "/images/corpo/barriga.png",
      },
      {
        id: "braco",
        label: "Braço",
        image: "/images/corpo/braco.png",
      },
      { id: "mao", label: "Mão" },
      { id: "dedo", label: "Dedo" },
      { id: "quadril", label: "Quadril" },
      {
        id: "perna",
        label: "Perna",
        image: "/images/corpo/pernas.png",
      },
      { id: "joelho", label: "Joelho" },
      {
        id: "pes",
        label: "Pés",
        image: "/images/corpo/pes.png",
      },
    ],
  },
];
